/* ---------------------------------------------------
    Auths
----------------------------------------------------- */

// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// USER LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

// REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// PASSWORD EDIT
export const PASSWORD_EDIT_REQUEST = "PASSWORD_EDIT_REQUEST";
export const PASSWORD_EDIT_SUCCESS = "PASSWORD_EDIT_SUCCESS";
export const PASSWORD_EDIT_FAILURE = "PASSWORD_EDIT_FAILURE";

/* ---------------------------------------------------
    Missions
----------------------------------------------------- */

// MISSIONSET LOAD
export const MISSIONSET_LOAD_REQUEST = "MISSIONSET_LOAD_REQUEST";
export const MISSIONSET_LOAD_SUCCESS = "MISSIONSET_LOAD_SUCCESS";
export const MISSIONSET_LOAD_FAILURE = "MISSIONSET_LOAD_FAILURE";

// MISSIONSET ERROR CLEAR
export const MISSIONSET_ERROR_CLEAR_REQUEST = "MISSIONSET_ERROR_CLEAR_REQUEST";

/* ---------------------------------------------------
    Party
----------------------------------------------------- */

// PARTY CREATE
export const PARTY_CREATE_REQUEST = "PARTY_CREATE_REQUEST";
export const PARTY_CREATE_SUCCESS = "PARTY_CREATE_SUCCESS";
export const PARTY_CREATE_FAILURE = "PARTY_CREATE_FAILURE";

// PARTY LOAD
export const PARTY_LOAD_REQUEST = "PARTY_LOAD_REQUEST";
export const PARTY_LOAD_SUCCESS = "PARTY_LOAD_SUCCESS";
export const PARTY_LOAD_FAILURE = "PARTY_LOAD_FAILURE";

// PARTICIPATE PARTY
export const PARTICIPATE_REQUEST = "PARTICIPATE_REQUEST";
export const PARTICIPATE_SUCCESS = "PARTICIPATE_SUCCESS";
export const PARTICIPATE_FAILURE = "PARTICIPATE_FAILURE";

// CHANGE JUDGE
export const CHANGE_JUDGE_REQUEST = "CHANGE_JUDGE_REQUEST";
export const CHANGE_JUDGE_SUCCESS = "CHANGE_JUDGE_SUCCESS";
export const CHANGE_JUDGE_FAILURE = "CHANGE_JUDGE_FAILURE";

// EXILE USER
export const EXILE_REQUEST = "EXILE_REQUEST";
export const EXILE_SUCCESS = "EXILE_SUCCESS";
export const EXILE_FAILURE = "EXILE_FAILURE";

// CHECK PARTY IS STARTED
export const PARTY_IS_STARTED_REQUEST = "PARTY_IS_STARTED_REQUEST";
export const PARTY_IS_STARTED_SUCCESS = "PARTY_IS_STARTED_SUCCESS";
export const PARTY_IS_STARTED_FAILURE = "PARTY_IS_STARTED_FAILURE";

// PARTY ERROR CLEAR
export const PARTY_ERROR_CLEAR_REQUEST = "PARTY_ERROR_CLEAR_REQUEST";

/* ---------------------------------------------------
    Party On
----------------------------------------------------- */

// PARTY START
export const PARTY_START_REQUEST = "PARTY_START_REQUEST";
export const PARTY_START_SUCCESS = "PARTY_START_SUCCESS";
export const PARTY_START_FAILURE = "PARTY_START_FAILURE";

// PARTY CONEECT
export const PARTY_CONNECT_REQUEST = "PARTY_CONNECT_REQUEST";
export const PARTY_CONNECT_SUCCESS = "PARTY_CONNECT_SUCCESS";
export const PARTY_CONNECT_FAILURE = "PARTY_CONNECT_FAILURE";

// MISSIONS
export const MISSION_SECOND = "MISSION_SECOND";
export const MISSION_SUBMIT = "MISSION_SUBMIT";
export const MISSION_ACCEPTED = "MISSION_ACCEPTED";
export const MISSION_DENIED = "MISSION_DENIED";
export const MISSION_VOTE_REQUEST = "MISSION_VOTE_REQUEST";
export const MISSION_UPVOTE = "MISSION_UPVOTE";
export const MISSION_DOWNVOTE = "MISSION_DOWNVOTE";

// TEST
export const TEST_REQUEST = "TEST_REQUEST";
